name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # This Step will take the code from the repository
      - name: "getting the code" 
        uses: actions/checkout@v4.1.5 # It is the Action checkout copied from Marketplace
        #with: in this case it is necessary if the code is in another repository. As we will use the current repository, you do not need to add it.
        # it is recogniozed automatically as current repo

        # 1-autenticar no docker hub docker login
        # 2-executar o comando de build da imagem e executar o comando para enviar a imagem para o docker hub

      # Login the Docker Hub  
      - name: "Authentication in Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image in the Docker Hub 
      - name: "Build and push the docker image"
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            bwake/pipeline-actions:v${{github.run_number}} 
            bwake/pipeline-actions:latest
          #Add the versioning as number of pipeline run will not repeat the version and also addin latest as best practice

 

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: "Getting the Code" 
        uses: actions/checkout@v4.1.5
      #1 - configuraç]ao do kube config  
      #2 - kubectl apply
      - name: "Configure the Kubernetes Context"
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig #Can be others as Service-principal, service account
          kubeconfig: ${{ secrets.K8S_CONFIG }} #It is a sensitive document so needs to secret it
      - name: Deploy of Manifest
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            bwake/pipeline-actions:v${{github.run_number}}   
          # Need to check in the manifest (YAML) if the image is the same as this

