name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # This Step will take the code from the repository
      - name: "getting the code" 
        uses: actions/checkout@v4.1.5 # It is the Action checkout copied from Marketplace
        #with: in this case it is necessary if the code is in another repository. As we will use the current repository, you do not need to add it.
        # it is recogniozed automatically as current repo

      # Login the Docker Hub  
      - name: "Authentication in Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          

  ###passo a passo da construção da imagem e o envio do docker registry
  # 1-autenticar no docker hub docker login
  # 2-executar o comando de build da imagem
  # 3-executar o comando para enviar a imagem para o docker hub



